### ISSUE TITLE
Code duplication

### ISSUE THREAD

**Issue by ostrichby** [igorvinnikov/godel.mastery#5]
Try to extract duplicated code into a function

https://github.com/igorvinnikov/godel.mastery/blob/eb395bb07d9f4f90f9101ac446fe944be0c6f9c2/Task1/index.php#L36

**Comment by igorvinnikov** [comment]
I've made 2 functions for values and date calculation. When I replace strings with needed values, they are different ways to show message in 2 modes. So, I haven't figured out to extract it into a function.
